### ISSUE TITLE
StackOverflowException in LoadRecursively when serialising a Record

### ISSUE THREAD

**Issue by runemoennike** [lawrence-laz/Extensions.Configuration.Object#5]
C# Records have a compiler generated `Type EqualityContract` property, once they get compiled into classes. When loading such a class, LoadRecursively fails with a StackOverflowException.

The property should not be loaded, I would say, but currently only fields are ignored when they have the `CompilerGenerated ` attribute. I propose to check properties in the same way, and I will make a PR with this implemented.

For reference, here is a new unit test case that fails in the current implementation:

```
    public class RecordObjectTest
    {
        internal record MyConfiguration
        {
            public SubRecordConfiguration SubRecord;
            public string MyKey;
        }

        internal record SubRecordConfiguration
        {
            public string Title;
            public string Name;
            public int Age;
        }

        [Fact]
        public void AddObject_WithClassObject_ShouldLoadFieldsIntoConfiguration()
        {
            var configuration = new ConfigurationBuilder()
                .AddObject(new MyConfiguration
                {
                    SubRecord = new SubRecordConfiguration
                    {
                        Title = "Editor",
                        Name = "Joe Smith",
                        Age = 33
                    },
                    MyKey = "My appsettings.json Value",
                })
                .Build();

            configuration["SubRecord:Title"].Should().Be("Editor");
            configuration["SubRecord:Name"].Should().Be("Joe Smith");
            configuration["SubRecord:Age"].Should().Be("33");
            configuration["MyKey"].Should().Be("My appsettings.json Value");
        }
    }

```

**Comment by lawrence-laz** [comment]
Makes sense, waiting for a PR 👍

**Comment by runemoennike** [comment]
Done :) I'm not sure if the check for anonymous classes is necessary or wanted?

**Comment by lawrence-laz** [comment]
Thanks, I'll look through it after work

**Comment by lawrence-laz** [comment]
I had a few minutes so looked at it now. All looks good besides that single test method name.

Regarding the check for anonymous class -- I'm not sure, looking at currently decompiled code anonymous class' properties do not have `CompilerGeneratedAttribute`, but this might have changed between versions?
I think we can leave the check for now, just to be safe.

**Comment by runemoennike** [comment]
Yes, that was my idea also.

The name should be fixed now.

**Comment by lawrence-laz** [comment]
Published to nuget.org as version `1.1.1` it should soon become publicly available.

**Comment by runemoennike** [comment]
Thank you for the quick responses!
